name: test_jaspr
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.16.2

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.11
  jaspr_builder: ^0.16.2
  jaspr_lints: ^0.1.2
  lints: ^3.0.0

jaspr:
  mode: client

